create table if not exists public.machine_states (
  machine_id text primary key,
  store_id text not null default '',
  display_name text not null default '',
  machine_type text not null default 'generic',
  game_url text not null default '',
  pool_id text not null default '',
  capabilities jsonb not null default '{}'::jsonb,
  locked boolean not null default false,
  reset_serial integer not null default 0,
  current_session_id text not null default '',
  current_player_name text not null default '',
  last_snapshot jsonb,
  last_ended_session jsonb,
  updated_at_ms bigint not null default 0,
  assigned_setting integer not null default 1,
  updated_at timestamptz not null default now()
);

create table if not exists public.issued_passwords (
  password text primary key,
  machine_id text not null,
  player_name text not null default '',
  status text not null default 'issued',
  issued_at_ms bigint not null default 0,
  used_at_ms bigint not null default 0,
  session_id text not null default ''
);

create table if not exists public.sessions (
  session_id text primary key,
  token text not null default '',
  password text not null default '',
  machine_id text not null,
  player_name text not null default '',
  status text not null default 'active',
  started_at_ms bigint not null default 0,
  ended_at_ms bigint not null default 0,
  reset_serial_at_start integer not null default 0,
  start_snapshot jsonb,
  result_record jsonb,
  sheets jsonb
);

create table if not exists public.machine_commands (
  id bigint generated by default as identity primary key,
  machine_id text not null,
  command jsonb not null,
  created_at_ms bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.session_results (
  id bigint generated by default as identity primary key,
  ended_at_ms bigint not null default 0,
  machine_id text not null default '',
  record jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists machine_commands_poll_idx on public.machine_commands(machine_id, id);
create index if not exists session_results_ended_idx on public.session_results(ended_at_ms desc);
create index if not exists issued_passwords_issued_idx on public.issued_passwords(issued_at_ms desc);


alter table public.sessions add column if not exists start_snapshot jsonb;
alter table public.machine_states add column if not exists store_id text not null default '';
alter table public.machine_states add column if not exists machine_type text not null default 'generic';
alter table public.machine_states add column if not exists game_url text not null default '';
alter table public.machine_states add column if not exists pool_id text not null default '';
alter table public.machine_states add column if not exists capabilities jsonb not null default '{}'::jsonb;

-- 店舗ごとに独立したJACsPOT共有プール用。投入・当選APIは次段階で接続する。
create table if not exists public.jackpot_pools (
  store_id text not null,
  pool_id text not null,
  current_pt bigint not null default 0 check (current_pt >= 0),
  contribution_rate numeric(6,5) not null default 0.1,
  version bigint not null default 0,
  updated_at timestamptz not null default now(),
  primary key (store_id, pool_id)
);

create table if not exists public.jackpot_events (
  event_id uuid primary key default gen_random_uuid(),
  store_id text not null,
  pool_id text not null,
  machine_id text not null,
  event_type text not null check (event_type in ('contribution', 'payout', 'adjustment')),
  amount_pt bigint not null,
  balance_after_pt bigint not null check (balance_after_pt >= 0),
  idempotency_key text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists jackpot_events_pool_idx
  on public.jackpot_events(store_id, pool_id, created_at desc);

-- 1回転ごとの10%積立を、複数台から同時に受けても取りこぼさず加算する。
create or replace function public.jackpot_pool_contribute(
  p_store_id text,
  p_pool_id text,
  p_machine_id text,
  p_amount_pt bigint,
  p_idempotency_key text
)
returns table(current_pt bigint, version bigint, applied boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_pt bigint;
  v_version bigint;
  v_existing_balance bigint;
begin
  if coalesce(p_store_id, '') = '' or coalesce(p_pool_id, '') = '' or coalesce(p_machine_id, '') = '' then
    raise exception 'store_id, pool_id and machine_id are required';
  end if;
  if p_amount_pt <= 0 or coalesce(p_idempotency_key, '') = '' then
    raise exception 'positive amount_pt and idempotency_key are required';
  end if;

  insert into public.jackpot_pools(store_id, pool_id)
  values (p_store_id, p_pool_id)
  on conflict (store_id, pool_id) do nothing;

  select jp.current_pt, jp.version
    into v_current_pt, v_version
  from public.jackpot_pools jp
  where jp.store_id = p_store_id and jp.pool_id = p_pool_id
  for update;

  select je.balance_after_pt
    into v_existing_balance
  from public.jackpot_events je
  where je.idempotency_key = p_idempotency_key;

  if found then
    return query select v_current_pt, v_version, false;
    return;
  end if;

  update public.jackpot_pools jp
  set current_pt = jp.current_pt + p_amount_pt,
      version = jp.version + 1,
      updated_at = now()
  where jp.store_id = p_store_id and jp.pool_id = p_pool_id
  returning jp.current_pt, jp.version into v_current_pt, v_version;

  insert into public.jackpot_events(
    store_id, pool_id, machine_id, event_type, amount_pt, balance_after_pt, idempotency_key
  ) values (
    p_store_id, p_pool_id, p_machine_id, 'contribution', p_amount_pt, v_current_pt, p_idempotency_key
  );

  return query select v_current_pt, v_version, true;
end;
$$;

-- 3rdステージのJP成立時に共有残高を一括払い出しし、同じトランザクション内で0へ戻す。
create or replace function public.jackpot_pool_claim(
  p_store_id text,
  p_pool_id text,
  p_machine_id text,
  p_idempotency_key text
)
returns table(paid_pt bigint, current_pt bigint, version bigint, applied boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_paid_pt bigint;
  v_version bigint;
  v_existing_paid bigint;
  v_existing_balance bigint;
begin
  if coalesce(p_store_id, '') = '' or coalesce(p_pool_id, '') = '' or coalesce(p_machine_id, '') = '' then
    raise exception 'store_id, pool_id and machine_id are required';
  end if;
  if coalesce(p_idempotency_key, '') = '' then
    raise exception 'idempotency_key is required';
  end if;

  insert into public.jackpot_pools(store_id, pool_id)
  values (p_store_id, p_pool_id)
  on conflict (store_id, pool_id) do nothing;

  select jp.current_pt, jp.version
    into v_paid_pt, v_version
  from public.jackpot_pools jp
  where jp.store_id = p_store_id and jp.pool_id = p_pool_id
  for update;

  select je.amount_pt, je.balance_after_pt
    into v_existing_paid, v_existing_balance
  from public.jackpot_events je
  where je.idempotency_key = p_idempotency_key;

  if found then
    return query select v_existing_paid, v_paid_pt, v_version, false;
    return;
  end if;

  update public.jackpot_pools jp
  set current_pt = 0,
      version = jp.version + 1,
      updated_at = now()
  where jp.store_id = p_store_id and jp.pool_id = p_pool_id
  returning jp.version into v_version;

  insert into public.jackpot_events(
    store_id, pool_id, machine_id, event_type, amount_pt, balance_after_pt, idempotency_key
  ) values (
    p_store_id, p_pool_id, p_machine_id, 'payout', v_paid_pt, 0, p_idempotency_key
  );

  return query select v_paid_pt, 0::bigint, v_version, true;
end;
$$;

revoke all on function public.jackpot_pool_contribute(text, text, text, bigint, text) from public, anon, authenticated;
revoke all on function public.jackpot_pool_claim(text, text, text, text) from public, anon, authenticated;
grant execute on function public.jackpot_pool_contribute(text, text, text, bigint, text) to service_role;
grant execute on function public.jackpot_pool_claim(text, text, text, text) to service_role;
