create table if not exists public.machine_states (
  machine_id text primary key,
  store_id text not null default '',
  display_name text not null default '',
  machine_type text not null default 'generic',
  game_url text not null default '',
  pool_id text not null default '',
  capabilities jsonb not null default '{}'::jsonb,
  locked boolean not null default false,
  reset_serial integer not null default 0,
  current_session_id text not null default '',
  current_player_name text not null default '',
  last_snapshot jsonb,
  last_ended_session jsonb,
  updated_at_ms bigint not null default 0,
  assigned_setting integer not null default 1,
  updated_at timestamptz not null default now()
);

create table if not exists public.issued_passwords (
  password text primary key,
  machine_id text not null,
  player_name text not null default '',
  status text not null default 'issued',
  issued_at_ms bigint not null default 0,
  used_at_ms bigint not null default 0,
  session_id text not null default ''
);

create table if not exists public.sessions (
  session_id text primary key,
  token text not null default '',
  password text not null default '',
  machine_id text not null,
  player_name text not null default '',
  status text not null default 'active',
  started_at_ms bigint not null default 0,
  ended_at_ms bigint not null default 0,
  reset_serial_at_start integer not null default 0,
  start_snapshot jsonb,
  result_record jsonb,
  sheets jsonb
);

create table if not exists public.machine_commands (
  id bigint generated by default as identity primary key,
  machine_id text not null,
  command jsonb not null,
  created_at_ms bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.session_results (
  id bigint generated by default as identity primary key,
  ended_at_ms bigint not null default 0,
  machine_id text not null default '',
  record jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists machine_commands_poll_idx on public.machine_commands(machine_id, id);
create index if not exists session_results_ended_idx on public.session_results(ended_at_ms desc);
create index if not exists issued_passwords_issued_idx on public.issued_passwords(issued_at_ms desc);


alter table public.sessions add column if not exists start_snapshot jsonb;
alter table public.machine_states add column if not exists store_id text not null default '';
alter table public.machine_states add column if not exists machine_type text not null default 'generic';
alter table public.machine_states add column if not exists game_url text not null default '';
alter table public.machine_states add column if not exists pool_id text not null default '';
alter table public.machine_states add column if not exists capabilities jsonb not null default '{}'::jsonb;

-- 店舗ごとに独立したJACsPOT共有プール用。投入・当選APIは次段階で接続する。
create table if not exists public.jackpot_pools (
  store_id text not null,
  pool_id text not null,
  current_pt bigint not null default 0 check (current_pt >= 0),
  contribution_rate numeric(6,5) not null default 0.1,
  version bigint not null default 0,
  updated_at timestamptz not null default now(),
  primary key (store_id, pool_id)
);

create table if not exists public.jackpot_events (
  event_id uuid primary key default gen_random_uuid(),
  store_id text not null,
  pool_id text not null,
  machine_id text not null,
  event_type text not null check (event_type in ('contribution', 'payout', 'adjustment')),
  amount_pt bigint not null,
  balance_after_pt bigint not null check (balance_after_pt >= 0),
  idempotency_key text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists jackpot_events_pool_idx
  on public.jackpot_events(store_id, pool_id, created_at desc);
